/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app1;

import java.awt.Component;
import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author DELL
 */
public class Control extends javax.swing.JFrame {

    /**
     * Creates new form Control
     */
    public Control() {
        initComponents();
        addTableHeader();
    }
    JFrameViewBtn viewbtn = new JFrameViewBtn();
    SelectedRowsJfram selectedRowsJfram = new SelectedRowsJfram();
    JFileChooser imageFile = new JFileChooser();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JlabelColor = new javax.swing.JLabel();
        Jlabelv_brand = new javax.swing.JLabel();
        jTextengin = new javax.swing.JTextField();
        jTextCost = new javax.swing.JTextField();
        jTextcapacity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jComboBoxSelected = new javax.swing.JComboBox();
        jRadioButtonM = new javax.swing.JRadioButton();
        jRadioButtonA = new javax.swing.JRadioButton();
        JlabelEngin = new javax.swing.JLabel();
        JlabelCapacity = new javax.swing.JLabel();
        JlabelModel_name = new javax.swing.JLabel();
        jTextbrand = new javax.swing.JTextField();
        jTextModel_name = new javax.swing.JTextField();
        JlabelCost = new javax.swing.JLabel();
        jTextcolor = new javax.swing.JTextField();
        jLabelImage = new javax.swing.JLabel();
        jButtonChooseImage = new javax.swing.JButton();
        jButtonMoveUP = new javax.swing.JButton();
        jButtonMoveDown = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        merna = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 840, 780));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Car Information");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 60));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlabelColor.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        JlabelColor.setText("Vehicle Color");
        jPanel2.add(JlabelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 190, -1));

        Jlabelv_brand.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Jlabelv_brand.setText("Vehicle Brand");
        jPanel2.add(Jlabelv_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 210, -1));

        jTextengin.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jTextengin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextengin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextenginActionPerformed(evt);
            }
        });
        jPanel2.add(jTextengin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 270, 50));

        jTextCost.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jTextCost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 270, 50));

        jTextcapacity.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jTextcapacity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextcapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 270, 50));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 820, -1, 50));

        jButtonView.setBackground(new java.awt.Color(0, 153, 153));
        jButtonView.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jButtonView.setText("View Selected Car");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonView, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 930, -1, 40));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jButton3.setText("Export Excel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 880, 190, 40));

        jButtonReset.setBackground(new java.awt.Color(0, 153, 153));
        jButtonReset.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 820, 110, 50));

        jComboBoxSelected.setBackground(new java.awt.Color(0, 153, 153));
        jComboBoxSelected.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jComboBoxSelected.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010" }));
        jComboBoxSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectedActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, -1, -1));

        jRadioButtonM.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jRadioButtonM);
        jRadioButtonM.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jRadioButtonM.setText("Manual");
        jRadioButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 670, 120, -1));

        jRadioButtonA.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jRadioButtonA);
        jRadioButtonA.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jRadioButtonA.setText("Automatic");
        jPanel2.add(jRadioButtonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 670, 150, -1));

        JlabelEngin.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        JlabelEngin.setText("Engine Efficiency");
        jPanel2.add(JlabelEngin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        JlabelCapacity.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        JlabelCapacity.setText("Vehicle Capcity");
        jPanel2.add(JlabelCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 220, -1));

        JlabelModel_name.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        JlabelModel_name.setText("Model Name");
        jPanel2.add(JlabelModel_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 180, -1));

        jTextbrand.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jTextbrand.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextbrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextbrandActionPerformed(evt);
            }
        });
        jPanel2.add(jTextbrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 270, 50));

        jTextModel_name.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jTextModel_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextModel_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextModel_nameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextModel_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 270, 50));

        JlabelCost.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        JlabelCost.setText("Vehicle Cost");
        jPanel2.add(JlabelCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 180, -1));

        jTextcolor.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jTextcolor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 270, 50));
        jPanel2.add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 700, 190, 110));

        jButtonChooseImage.setBackground(new java.awt.Color(0, 153, 153));
        jButtonChooseImage.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jButtonChooseImage.setText("Choose Image");
        jButtonChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseImageActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonChooseImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, -1, 50));

        jButtonMoveUP.setBackground(new java.awt.Color(0, 153, 153));
        jButtonMoveUP.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jButtonMoveUP.setText("Move UP");
        jButtonMoveUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoveUPActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonMoveUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 880, 190, 40));

        jButtonMoveDown.setBackground(new java.awt.Color(0, 153, 153));
        jButtonMoveDown.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jButtonMoveDown.setText("Move Down");
        jButtonMoveDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoveDownActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonMoveDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 880, 220, 40));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jButton2.setText("Import (Excel)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 930, 190, 40));

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jButton4.setText("Delete Selected Car");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 820, 240, 50));

        jButton5.setBackground(new java.awt.Color(0, 153, 153));
        jButton5.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jButton5.setText("View Cars' List");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 930, -1, 40));

        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 270, 50));

        jTextField3.setBackground(new java.awt.Color(102, 102, 102));
        jTextField3.setBorder(null);
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 270, 50));

        jTextField4.setBackground(new java.awt.Color(102, 102, 102));
        jTextField4.setBorder(null);
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 270, 50));

        jTextField5.setBackground(new java.awt.Color(102, 102, 102));
        jTextField5.setBorder(null);
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 270, 50));

        jTextField6.setBackground(new java.awt.Color(102, 102, 102));
        jTextField6.setBorder(null);
        jTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 270, 50));

        jTextField7.setBackground(new java.awt.Color(102, 102, 102));
        jTextField7.setBorder(null);
        jTextField7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 270, 50));

        jButton6.setBackground(new java.awt.Color(0, 153, 153));
        jButton6.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 820, -1, 50));

        jButton7.setBackground(new java.awt.Color(0, 153, 153));
        jButton7.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jButton7.setText("Log Out");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 980, 180, 40));
        jPanel2.add(merna, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 680, 60, 40));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jLabel1.setText("Vehicle Type");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 620, 200, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jLabel3.setText("Year Of Purchase");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextenginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextenginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextenginActionPerformed

    //declare all variables
    DefaultTableModel model;
    String vEngineEfficiency = "";
    String vColor = "";
    String vCapacity = "";
    String model_name = "";
    String vBrand = "";
    String vCost = "";
    String type = "";
    String year = "";
    String ImageSelectedPath = "";
    String excelImagePath = "";

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        vEngineEfficiency = jTextengin.getText();
        vCapacity = jTextcapacity.getText();
        vColor = jTextcolor.getText();
        model_name = jTextModel_name.getText();
        vBrand = jTextbrand.getText();
        vCost = jTextCost.getText();

        if (jRadioButtonM.isSelected()) {
            type = "Manual";
        } else if (jRadioButtonA.isSelected()) {
            type = "Automatic";
        }

        year = jComboBoxSelected.getSelectedItem().toString();
        JLabel imageLabel = new JLabel();
        ImageIcon imageIcon = new ImageIcon(ImageSelectedPath);
        //set size of image (60 for width, 60 for Height)
        Image imageIc = imageIcon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);

        //set Description
        ImageIcon excelSetDescription = new ImageIcon(imageIc);
        excelSetDescription.setDescription(ImageSelectedPath);

        //store image in jlabel
        imageLabel.setIcon(excelSetDescription);

        if (vEngineEfficiency.isEmpty() || vColor.isEmpty() || vCapacity.isEmpty() || model_name.isEmpty() || vBrand.isEmpty() || vCost.isEmpty() || year.isEmpty() || type.isEmpty() || ImageSelectedPath.isEmpty()) {
            JOptionPane.showMessageDialog(null, "You Should Complete All Fields");
        } else {
            model.addRow(new Object[]{vEngineEfficiency, vBrand, vCapacity, model_name,  vCost, vColor, type, year, imageLabel});

            JOptionPane.showMessageDialog(null, "Information is Added");

            //clear Fields after adding information
            clearFields();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void addTableHeader() {

        model = (DefaultTableModel) jTable1.getModel();
        Object[] newIdentifiers = new Object[]{"Engine Efficiency", "Brand", "Capacity", "Model Name", "Cost",  "Color", "Type", "Year", "Image"};
        model.setColumnIdentifiers(newIdentifiers);

        // get image col and override TableCellRenderer class components method getTableCellRendererComponent
        jTable1.getColumn("Image").setCellRenderer(new myTableCellRenderer());
    }

    class myTableCellRenderer implements TableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int col) {
            //change col min-width and max-width 
            TableColumn tb = jTable1.getColumn("Image");
            tb.setMaxWidth(60);
            tb.setMinWidth(60);
            jTable1.setRowHeight(60);
            return (Component) value;
        }
    }


    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextbrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextbrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextbrandActionPerformed

    private void jTextModel_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextModel_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextModel_nameActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int rowSelected = jTable1.getSelectedRow();
        //show info of table in input fields
        jTextengin.setText(model.getValueAt(rowSelected, 0).toString());
        jTextbrand.setText(model.getValueAt(rowSelected, 1).toString());
        jTextcapacity.setText(model.getValueAt(rowSelected, 2).toString());
        jTextModel_name.setText(model.getValueAt(rowSelected, 3).toString());
        jTextCost.setText(model.getValueAt(rowSelected, 4).toString());
        jTextcolor.setText(model.getValueAt(rowSelected, 5).toString());

        String tablegender = model.getValueAt(rowSelected, 6).toString();
        if (tablegender.equals("Manual")) {
            jRadioButtonM.setSelected(true);
        } else if (tablegender.equals("Automatic")) {
            jRadioButtonA.setSelected(true);
        }
        String selectedFromMenu = model.getValueAt(rowSelected, 7).toString();

        for (int i = 0; i < jComboBoxSelected.getItemCount(); i++) {
            if (jComboBoxSelected.getItemAt(i).toString().equalsIgnoreCase(selectedFromMenu)) {
                jComboBoxSelected.setSelectedIndex(i);
            }
        }
        //the image is stored as imageIcon in Jlabel
        //the image is stored in the 4th col
        JLabel imagejl = (JLabel) model.getValueAt(rowSelected, 8);
        //retrieve image icon from jlabel
        //store image icon in imageIcon type var
        ImageIcon imageJlIcon = (ImageIcon) imagejl.getIcon();
        //fix size of image to fit to jlabel
        Image imageJlFit = imageJlIcon.getImage().getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH);
        //show selected image in jlabel
        jLabelImage.setIcon(new ImageIcon(imageJlFit));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseImageActionPerformed

        //setting Default Browser location
        imageFile = new JFileChooser("C:\\Users\\DELL\\Documents\\NetBeansProjects\\App1\\images");
        //Filter image extensions
        FileNameExtensionFilter fileEx = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg", "jfif");
        imageFile.addChoosableFileFilter(fileEx);
        int showOpenDialogue = imageFile.showOpenDialog(null);

        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File ImageSelectedFile = imageFile.getSelectedFile();
            ImageSelectedPath = ImageSelectedFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, ImageSelectedPath);

            //show image on JlabelImage
            ImageIcon imageIcon = new ImageIcon(ImageSelectedPath);

            //control size of image
            Image image = imageIcon.getImage().getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH);
            jLabelImage.setIcon(new ImageIcon(image));

        }

    }//GEN-LAST:event_jButtonChooseImageActionPerformed

    //Move UP btn
    private void jButtonMoveUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoveUPActionPerformed
        //get Jtable selected row
        int currentRowSelected = jTable1.getSelectedRow();
        if (currentRowSelected > 0) {
            //substact one from current row to move up
            model.moveRow(currentRowSelected, currentRowSelected, currentRowSelected - 1);
            jTable1.getSelectionModel().setSelectionInterval(currentRowSelected - 1, currentRowSelected - 1);
        } else {
            JOptionPane.showMessageDialog(null, "you've reached the end.\nClick Move Down Button");
        }

        System.out.println("Selected Row - " + currentRowSelected);
    }//GEN-LAST:event_jButtonMoveUPActionPerformed

    //Move Down btn 
    private void jButtonMoveDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoveDownActionPerformed
        int currentRowSelected = jTable1.getSelectedRow();
        if (currentRowSelected < jTable1.getRowCount() - 1) {
            //substact one from current row to move down
            model.moveRow(currentRowSelected, currentRowSelected, currentRowSelected + 1);
            jTable1.getSelectionModel().setSelectionInterval(currentRowSelected + 1, currentRowSelected + 1);
        } else {
            JOptionPane.showMessageDialog(null, "you've reached the end.\nClick Move UP Button");
        }

        System.out.println("Selected Row - " + currentRowSelected);
    }//GEN-LAST:event_jButtonMoveDownActionPerformed

    //Reset Btn
    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        //cal fn to clear input Fields
        clearFields();

    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        viewbtn.setVisible(true);
        //prevent Closing parent's frame
        viewbtn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //Get Selected Row
        int newFrameSelectedRow = jTable1.getSelectedRow();
        //check if row is selected
        if (newFrameSelectedRow == -1) {
            //show Error Message
            viewbtn.jLabelSelectedRowMessage.setText("NO Row is Selected");

        } else {
            //Clear Error Message First
            viewbtn.jLabelSelectedRowMessage.setText(null);
            System.out.println("Selected Row Value = " + newFrameSelectedRow);

            //Retrieving Jtable Selected Row
            String newEngine = model.getValueAt(newFrameSelectedRow, 0).toString();
            String newVbrand = model.getValueAt(newFrameSelectedRow, 1).toString();
            String newCapacity = model.getValueAt(newFrameSelectedRow, 2).toString();
            String newModel = model.getValueAt(newFrameSelectedRow, 3).toString();
            String newCost = model.getValueAt(newFrameSelectedRow, 4).toString();
            String newColor = model.getValueAt(newFrameSelectedRow, 5).toString();
            String newType = model.getValueAt(newFrameSelectedRow, 6).toString();
            String newSelected = model.getValueAt(newFrameSelectedRow, 7).toString();
            JLabel newImageJl = (JLabel) model.getValueAt(newFrameSelectedRow, 8);
            ImageIcon newImageIcon = (ImageIcon) newImageJl.getIcon();

            //Resize image to fit to jlabel
            Image newImage = newImageIcon.getImage().getScaledInstance(viewbtn.newFrameJLabelFieldImage.getWidth(), viewbtn.newFrameJLabelFieldImage.getHeight(), Image.SCALE_SMOOTH);
            //show Selected Row in New Frame input Fields
            viewbtn.newFrameJTextFieldEngine.setText(newEngine);
            viewbtn.newFrameJTextFieldColor.setText(newColor);
            viewbtn.newFrameJTextFieldCapacity.setText(newCapacity);
            viewbtn.newFrameJTextFieldModel.setText(newModel);
            viewbtn.newFrameJTextFieldVbrand.setText(newVbrand);
            viewbtn.newFrameJTextFieldCost.setText(newCost);
            viewbtn.newFrameJTextFieldType.setText(newType);
            viewbtn.newFrameJTextFieldSelected.setText(newSelected);
            viewbtn.newFrameJLabelFieldImage.setIcon(new ImageIcon(newImage));

        }

    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        FileOutputStream excelFOS = null;
        BufferedOutputStream excelBOS = null;
        XSSFWorkbook jtableExcel = null;

        //choose Location for Saving Excel File
        JFileChooser excelFile = new JFileChooser();
        //change title of dialog box
        excelFile.setDialogTitle("Save AS");
        //onliny filter files with extension()
        FileNameExtensionFilter excelExt = new FileNameExtensionFilter("EXCEL FILE", "xls", "xlsx", "xlsm");
        excelFile.setFileFilter(excelExt);
        int selectedExcel = excelFile.showSaveDialog(null);

        //check if Save Btn is clicked
        if (selectedExcel == JFileChooser.APPROVE_OPTION) {

            try {
                // import excel poi libraries to netbeans
                jtableExcel = new XSSFWorkbook();
                XSSFSheet excelSheet = jtableExcel.createSheet("JTable Sheet");
                //to get jtable row & col
                for (int i = 0; i < model.getRowCount(); i++) {
                    XSSFRow excelRow = excelSheet.createRow(i);
                    for (int j = 0; j < 9; j++) {
                        XSSFCell excelCell = excelRow.createCell(j);

                        //Get ImageNames From Jlabel
                        //Get the last col
                        if (j == model.getColumnCount() - 1) {
                            JLabel excelJL = (JLabel) model.getValueAt(i, j);
                            ImageIcon excelImageIcon = (ImageIcon) excelJL.getIcon();

                            //Before Retrieving the description of image first set it
                            excelImagePath = excelImageIcon.getDescription();
                        }
                        excelCell.setCellValue(model.getValueAt(i, j).toString());

                        //change val of the 9th col to image path
                        if (excelCell.getColumnIndex() == model.getColumnCount() - 1) {
                            excelCell.setCellValue(excelImagePath);
                        }
                    }
                }
                //append xlsx file exrension so selected files to create name of file
                excelFOS = new FileOutputStream(excelFile.getSelectedFile() + ".xlsx");
                excelBOS = new BufferedOutputStream(excelFOS);
                jtableExcel.write(excelBOS);
                JOptionPane.showMessageDialog(null, "Exported Successfully");
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            } finally {
                try {
                    if (excelBOS != null) {
                        excelBOS.close();
                    }
                    if (excelFOS != null) {
                        excelFOS.close();
                    }

                    if (jtableExcel != null) {
                        jtableExcel.close();
                    }
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        File excelFile;
        FileInputStream excelFIS = null;
        BufferedInputStream excelBIS = null;
        XSSFWorkbook excelImport = null;
        //select Default Path
        String defaultCurrentDirectoryPath = "C:\\Users\\DELL\\Documents\\NetBeansProjects\\App1";
        JFileChooser excelFileChooser = new JFileChooser(defaultCurrentDirectoryPath);

        //filter Excel Files
        FileNameExtensionFilter excelFilter = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        excelFileChooser.setFileFilter(excelFilter);

        //set Dialog Title
        excelFileChooser.setDialogTitle("Select Excel File");

        int excelChooser = excelFileChooser.showOpenDialog(null);

        //if open Btn is Clicked
        if (excelChooser == JFileChooser.APPROVE_OPTION) {

            try {
                excelFile = excelFileChooser.getSelectedFile();
                excelFIS = new FileInputStream(excelFile);
                excelBIS = new BufferedInputStream(excelFIS);

                excelImport = new XSSFWorkbook(excelBIS);
                XSSFSheet excelSheet = excelImport.getSheetAt(0);

                //loop through excel row and col
                for (int i = 0; i < excelSheet.getLastRowNum(); i++) {
                    XSSFRow excelRow = excelSheet.getRow(i);
                    XSSFCell excelEngine = excelRow.getCell(0);
                    XSSFCell excelVbrand = excelRow.getCell(1);
                    XSSFCell excelCapacity = excelRow.getCell(2);
                    XSSFCell excelmodel = excelRow.getCell(3);
                    XSSFCell excelCost = excelRow.getCell(4);
                    XSSFCell excelColor = excelRow.getCell(5);
                    XSSFCell excelType = excelRow.getCell(6);
                    XSSFCell excelSelected = excelRow.getCell(7);
                    XSSFCell excelImage = excelRow.getCell(8);

                    //Control size of images
                    JLabel excelJL = new JLabel(new ImageIcon(new ImageIcon(excelImage.toString()).getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH)));
                    model.addRow(new Object[]{excelEngine, excelVbrand, excelCapacity, excelmodel, excelCost, excelColor, excelType, excelSelected, excelJL});
                }
                JOptionPane.showMessageDialog(null, "Import Successfully");
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } finally {

                try {
                    if (excelFIS != null) {
                        excelFIS.close();
                    }
                    if (excelBIS != null) {
                        excelBIS.close();
                    }
                    if (excelImport != null) {
                        excelImport.close();
                    }
                } catch (IOException exp) {
                    JOptionPane.showMessageDialog(null, exp.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Delete selected Row
        int selectedRow = jTable1.getSelectedRow();

        //check if there's Selected Row
        if (selectedRow >= 0) {
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(null, "Row Deleted.");
        } else {
            JOptionPane.showMessageDialog(null, "Unable to Delete.");

        }
        //to clear
        clearFields();
        jLabelImage.setIcon(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        int[] viewSelectedRow = jTable1.getSelectedRows();

        Object[] newFormRows = new Object[9];
        for (int i = 0; i < viewSelectedRow.length; i++) {

            newFormRows[0] = model.getValueAt(viewSelectedRow[i], 0);
            newFormRows[1] = model.getValueAt(viewSelectedRow[i], 1);
            newFormRows[2] = model.getValueAt(viewSelectedRow[i], 2);
            newFormRows[3] = model.getValueAt(viewSelectedRow[i], 3);
            newFormRows[4] = model.getValueAt(viewSelectedRow[i], 4);
            newFormRows[5] = model.getValueAt(viewSelectedRow[i], 5);
            newFormRows[6] = model.getValueAt(viewSelectedRow[i], 6);
            newFormRows[7] = model.getValueAt(viewSelectedRow[i], 7);
            newFormRows[8] = model.getValueAt(viewSelectedRow[i], 8);

            selectedRowsJfram.SelectedRowsJFrameFromModel.addRow(newFormRows);
        }

        // selectedRowsJfram.setVisible(true);
        //pervent the new frame from closing the main frame
        //selectedRowsJfram.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.toBack();

        selectedRowsJfram.setVisible(true);
        selectedRowsJfram.toFront();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        vEngineEfficiency = jTextengin.getText();
        vCapacity = jTextcapacity.getText();
        vColor = jTextcolor.getText();
        model_name = jTextModel_name.getText();
        vBrand = jTextbrand.getText();
        vCost = jTextCost.getText();
        JLabel imageLabel = new JLabel();
        ImageIcon imageIcon = new ImageIcon(ImageSelectedPath);
        //set size of image (60 for width, 60 for Height)
        Image imageIc = imageIcon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);

        //set Description
        ImageIcon excelSetDescription = new ImageIcon(imageIc);
        excelSetDescription.setDescription(ImageSelectedPath);

        //store image in jlabel
        imageLabel.setIcon(excelSetDescription);
        if (jRadioButtonM.isSelected()) {
            type = "Manual";
        } else if (jRadioButtonA.isSelected()) {
            type = "Automatic";
        }

        year = jComboBoxSelected.getSelectedItem().toString();

        int newFrameSelectedRow = jTable1.getSelectedRow();
        //check if row is selected
        if (newFrameSelectedRow == -1) {
            System.out.println("error");

        } else {
            System.out.println("Selected Row Value = " + newFrameSelectedRow);
        }

        if (newFrameSelectedRow >= 0) {
            model.setValueAt(vEngineEfficiency, newFrameSelectedRow, 0);
            model.setValueAt(vBrand, newFrameSelectedRow, 1);
            model.setValueAt(vCapacity, newFrameSelectedRow, 2);
            model.setValueAt(model_name, newFrameSelectedRow, 3);
            model.setValueAt(vCost, newFrameSelectedRow, 4);
            model.setValueAt(vColor, newFrameSelectedRow, 5);
            model.setValueAt(type, newFrameSelectedRow, 6);
            model.setValueAt(year, newFrameSelectedRow, 7);
            model.setValueAt(imageLabel, newFrameSelectedRow, 8);

        } else {
            System.out.println("Update Error");
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.toBack();
        setVisible(false);
        Control control = new Control();
        control.toFront();
        control.setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jRadioButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMActionPerformed

    private void jComboBoxSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Control().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelCapacity;
    private javax.swing.JLabel JlabelColor;
    private javax.swing.JLabel JlabelCost;
    private javax.swing.JLabel JlabelEngin;
    private javax.swing.JLabel JlabelModel_name;
    private javax.swing.JLabel Jlabelv_brand;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonChooseImage;
    private javax.swing.JButton jButtonMoveDown;
    private javax.swing.JButton jButtonMoveUP;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonView;
    private javax.swing.JComboBox jComboBoxSelected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonA;
    private javax.swing.JRadioButton jRadioButtonM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextCost;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextModel_name;
    private javax.swing.JTextField jTextbrand;
    private javax.swing.JTextField jTextcapacity;
    private javax.swing.JTextField jTextcolor;
    private javax.swing.JTextField jTextengin;
    private javax.swing.JLabel merna;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        jTextengin.setText("");
        jTextcolor.setText("");
        jTextcapacity.setText("");
        jTextCost.setText("");
        jTextModel_name.setText("");
        jTextbrand.setText("");
        buttonGroup1.clearSelection();
        jComboBoxSelected.setSelectedIndex(0);
        jLabelImage.setIcon(null);
        //jLabelImage.setText("");
    }
}
