/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app1;

import javax.swing.*;

/**
 *
 * @author DELL
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        signName = new javax.swing.JTextField();
        signEmail = new javax.swing.JTextField();
        signPhone = new javax.swing.JTextField();
        signAddress = new javax.swing.JTextField();
        signPass = new javax.swing.JPasswordField();
        signConfrim = new javax.swing.JPasswordField();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SIGN UP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 90, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel3.setText("Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 90, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 140, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel5.setText("Confirm Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 260, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel6.setText("Phone");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 90, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 120, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 303, 120, 40));

        signName.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        signName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signName.setBorder(null);
        signName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                signNameKeyReleased(evt);
            }
        });
        jPanel1.add(signName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 290, 50));

        signEmail.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        signEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signEmail.setBorder(null);
        signEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                signEmailFocusLost(evt);
            }
        });
        signEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signEmailActionPerformed(evt);
            }
        });
        signEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                signEmailKeyReleased(evt);
            }
        });
        jPanel1.add(signEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 290, 50));

        signPhone.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        signPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signPhone.setBorder(null);
        signPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signPhoneActionPerformed(evt);
            }
        });
        jPanel1.add(signPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 290, 50));

        signAddress.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        signAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signAddress.setBorder(null);
        jPanel1.add(signAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 290, 50));

        signPass.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        signPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signPass.setBorder(null);
        signPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signPassActionPerformed(evt);
            }
        });
        jPanel1.add(signPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 290, 50));

        signConfrim.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        signConfrim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signConfrim.setBorder(null);
        signConfrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signConfrimActionPerformed(evt);
            }
        });
        jPanel1.add(signConfrim, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 290, 50));

        jRadioButtonMale.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jRadioButtonMale);
        jRadioButtonMale.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 110, 50));

        jRadioButtonFemale.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jRadioButtonFemale);
        jRadioButtonFemale.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jRadioButtonFemale.setText("Female");
        jPanel1.add(jRadioButtonFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 370, 130, 50));

        jButton1.setBackground(new java.awt.Color(0, 162, 162));
        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jButton1.setText("SIGN UP");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 523, 190, 70));

        jButton2.setBackground(new java.awt.Color(0, 162, 162));
        jButton2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jButton2.setText("BACK");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 523, 220, 70));

        jTextField5.setBackground(new java.awt.Color(102, 102, 102));
        jTextField5.setBorder(null);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 290, 50));

        jTextField6.setBackground(new java.awt.Color(102, 102, 102));
        jTextField6.setBorder(null);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 290, 50));

        jTextField7.setBackground(new java.awt.Color(102, 102, 102));
        jTextField7.setBorder(null);
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 290, 50));

        jTextField8.setBackground(new java.awt.Color(102, 102, 102));
        jTextField8.setBorder(null);
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 290, 50));

        jTextField9.setBackground(new java.awt.Color(102, 102, 102));
        jTextField9.setBorder(null);
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 290, 50));

        jTextField10.setBackground(new java.awt.Color(102, 102, 102));
        jTextField10.setBorder(null);
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 290, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1214, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String name = signName.getText();
        String email = signEmail.getText();
        String pass = signPass.getText();
        String confirmPass = signConfrim.getText();
        String phone = signPhone.getText();
        String address = signAddress.getText();
        boolean checkPass = false;
        boolean checkLetter = false, checkNum = false, checkSpecial = false;
        boolean passCheckLetter = false, passCheckNum = false, passCheckSpecial = false;
        boolean checkPhone = false;
        String gender = "";
        
        //Selected Gender
        if(jRadioButtonMale.isSelected()){
            gender = "Male";
        }
        else if(jRadioButtonFemale.isSelected()){
            gender = "Female";
        }
        
        
        //Validation of Password
        System.out.println("Pass");
        for (int i = 0; i <= pass.length() - 1; i++) {
            if ((pass.charAt(i) >= 'a' && pass.charAt(i) <= 'z') || (pass.charAt(i) >= 'A' && pass.charAt(i) <= 'Z')) {
                System.out.println("x = " + pass.charAt(i));
                passCheckLetter = true;
            }
            if (pass.charAt(i) >= '0' && pass.charAt(i) <= '9') {
                System.out.println("y = " + pass.charAt(i));
                passCheckNum = true;
            }
            if (pass.charAt(i) == '@' || pass.charAt(i) == '#' || pass.charAt(i) == '.' || pass.charAt(i) == '_' || pass.charAt(i) == '&') {
                System.out.println("z = " + pass.charAt(i));
                passCheckSpecial = true;
            }
        }
        
        if (pass.equals(confirmPass)) {
            checkPass = true;
        } else {
            checkPass = false;
        }

        //Validation of Email
        System.out.println("Email");
        for (int i = 0; i <= email.length() - 1; i++) {
            if ((email.charAt(i) >= 'a' && email.charAt(i) <= 'z') || (email.charAt(i) >= 'A' && email.charAt(i) <= 'Z')) {
                System.out.println("x = " + email.charAt(i));
                checkLetter = true;
            }
            if (email.charAt(i) >= '0' && email.charAt(i) <= '9') {
                System.out.println("y = " + email.charAt(i));
                checkNum = true;
            }
            if (email.charAt(i) == '@' || email.charAt(i) == '#' || email.charAt(i) == '.' || email.charAt(i) == '_' || email.charAt(i) == '&') {
                System.out.println("z = " + email.charAt(i));
                checkSpecial = true;
            }
        }
        
        
        //Validation of Phone
        System.out.println("Phone");
        for (int i = 0; i <= phone.length() - 1; i++) {
            
            //check if Phone number contains 11 digits or not
            if(phone.length() == 11 ){
                if (phone.charAt(i) >= '0' && phone.charAt(i) <= '9') {
                    System.out.println("number = " + phone.charAt(i));
                    checkPhone = true;
                }
            } 
            else{
                 checkPhone = false;
            }
        }
        
        Control control = new Control();
        
        //Validation of Sign Up
        //if there is no Entered value for name and password
        if ((name.equals("")) || (pass.equals("")) || (email.equals("")) || (phone.equals("")) || (confirmPass.equals("")) || (address.equals("") || (gender.equals("")))) {
            JOptionPane.showMessageDialog(this, "Please.\nEnter All information.");
        } else {
            if (checkPass == true && checkLetter == true && checkNum == true && checkSpecial == true && checkPhone == true && passCheckLetter == true && passCheckNum == true && passCheckSpecial == true) {
                JOptionPane.showMessageDialog(this, "Valid Sign UP.");
                
                //nada user
                control.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Sign UP.\nCheck Your Entered Information");
                if(checkPhone == false){
                    JOptionPane.showMessageDialog(this,"Phone Number must contain 11 digits, \nand they must be only Number.");
                }
                if(checkNum == false || checkSpecial == false || checkNum == false){
                    JOptionPane.showMessageDialog(this,"Email must contain Numbers[0-9], Letters and Special Character[@ , # , _ , . , &].");
                }
                
                if(checkPass == false){
                    JOptionPane.showMessageDialog(this,"Password and Confirm Password must be the same");
                    
                    //
                    if(passCheckNum == false || passCheckSpecial == false || passCheckNum == false){
                    JOptionPane.showMessageDialog(this,"Password must contain Numbers[0-9], Letters and Special Character[@ , # , _ , . , &].");
                }
                }
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void signEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signEmailKeyReleased

    }//GEN-LAST:event_signEmailKeyReleased

    private void signEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signEmailActionPerformed

    private void signEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signEmailFocusLost

    }//GEN-LAST:event_signEmailFocusLost

    private void signNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signNameKeyReleased

    }//GEN-LAST:event_signNameKeyReleased

    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void signPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signPassActionPerformed

    }//GEN-LAST:event_signPassActionPerformed

    private void signConfrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signConfrimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signConfrimActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
//         create an obj refers to Register frame
//        SignUp signUp = new SignUp();
//        signUp.setVisible(true);
        this.toBack();
        setVisible(false);
        Register register = new Register();
        register.toFront();
        register.setState(java.awt.Frame.NORMAL);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void signPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signPhoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField signAddress;
    private javax.swing.JPasswordField signConfrim;
    private javax.swing.JTextField signEmail;
    private javax.swing.JTextField signName;
    private javax.swing.JPasswordField signPass;
    private javax.swing.JTextField signPhone;
    // End of variables declaration//GEN-END:variables
}
